type Sichta = {
  id: number;
  zacatek: string;
  konec?: string | null;
  prace_zacatek ?: string | null;
  prace_konec?: string | null;
  delka_min?: number | null;
  pauza_min?: number | null;
  popis?: string | null;
  material?: string | null;
  km?: number | null;
  zakazka_id?: number | null;
  zakazka?: string | null;
  misto_id?: number | null;
  misto?: string | null;
  zakaznik_id?: number | null;
  zakaznik?: string | null;
  vozidlo_id?: number | null;
  vozidlo?: string | null;
  adresa_text?: string | null;
  user_id?: number | null;   
  user?: string | null;      
  drive_file_url?: string[] | null;
};